name: Build and Push Test App Docker Image

on:
  # push:      
  #   branches:
  #     - main  
  #   paths:    
  #     - 'docker/test/**'
  workflow_dispatch:  # Manual trigger

permissions:
  id-token: write
  contents: read

env:
  TF_LOG: DEBUG
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  AZURE_RESOURCE_GROUP: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}
  APP_REPO_PATH: ./docker/test
  IMAGE_NAME: test-app-image
  IMAGE_TAG: latest

jobs:
  check-infra:
    runs-on: ubuntu-latest
    environment: infra-ready  # this is required to access environment-scoped variables
    steps:
      - name: Fail if infra not ready
        run: |
          if [[ "${{ vars.INFRA_READY }}" != "true" ]]; then
            echo "Infrastructure is not ready. Please run the bootstrap workflow first."
            exit 1
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: [check-infra]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Check ACR access
      run: |
        echo "Pinging ACR: $REGISTRY"
        echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$REGISTRY_USERNAME" --password-stdin || {
          echo "❌ Failed to authenticate with ACR. Aborting build."
          exit 1
        }
        echo "✅ ACR login successful."

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.APP_REPO_PATH }}
        file: ${{ env.APP_REPO_PATH }}/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}