# .github/workflows/provision.yml

name: Provision Azure Infrastructure

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ main ]  # Also trigger on push to main

env:
  TF_LOG: DEBUG
  TF_VAR_github_token: ${{ secrets.GH_PAT_TOKEN }}
  TF_VAR_github_owner: ${{ github.repository_owner }}
  TF_VAR_github_repository: ${{ github.event.repository.name }}
  TF_VAR_resource_group_name: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}
  TF_VAR_location: ${{ secrets.TF_VAR_LOCATION }}
  TF_VAR_storage_account_name: ${{ secrets.TF_VAR_STORAGE_ACCOUNT_NAME }}
  TF_VAR_subscription_id: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    # Single Azure login with JSON credentials
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      working-directory: infra/main

    - name: Terraform Plan
      run: terraform plan
      working-directory: infra/main

    # This only runs on main branch pushes (not PRs)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: infra/main

  build-and-push:
    runs-on: ubuntu-latest
    needs: terraform
    # Only run if we're on main branch AND terraform succeeded
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest
          ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}


  deploy-app:
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    needs: [terraform, build-and-push]
    if: github.ref == 'refs/heads/main'
            
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
                "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }
        
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name my-app \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}