name: Deploy Azure Function App
permissions:
    id-token: write
    contents: read

on:
  workflow_dispatch:

env:
    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }} 
    FUNCTION_APP_NAME: ${{ secrets.TF_VAR_FUNCTION_APP_NAME }} # To be implemented in the Terraform module
    
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Azure Login via OIDC
        uses: azure/login@v2 # Use v2 for OIDC support
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Install Python dependencies into function directory
        run: |
          cd azure-functions/save-logs-app
          pip install -r requirements.txt -t .
          cd -

      - name: Zip Function App
        run: |
          cd azure-functions/save-logs-app
          zip -r ../../save_logs_function.zip . -x "*.git*" "*.DS_Store*"
          cd -

      - name: Deploy Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: save_logs_function.zip

      - name: Clean up
        run: |
          rm save_logs_function.zip
          echo "Function App deployed successfully!"


    