name: Deploy ADF Pipeline and Trigger

on:
  workflow_dispatch:

env:
  ADF_NAME: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}-adf       # ${{ secrets.ADF_NAME }} # make use of it or remove it
  RESOURCE_GROUP: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }} 
  LOCATION: westeurope
  SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
  ACI_NAME: ephemeral-job
  ACR_NAME: ${{ secrets.TF_VAR_CONTAINER_REGISTRY_NAME }}
  IMAGE_NAME: ${{ secrets.BRICK_PCASTER_IMAGE_NAME }}
  STORAGE_ACCOUNT_NAME: ${{ secrets.TF_VAR_STORAGE_ACCOUNT_NAME }}
  IDENTITY_RESOURCE_ID: ${{ secrets.IDENTITY_RESOURCE_ID }} # Managed Identity for ADF
  TRIGGER_NAME: DailyTrigger
  ADF_PIPELINE_NAME: RunEphemeralACI

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Generate pipeline JSON with env vars and create trigger JSON
      run: |
        echo "Generating pipeline.json and trigger.json with environment variables..."
        NOW=$(date -u -d "+2 minutes" +"%Y-%m-%dT%H:%M:%SZ")
        cat infra/adf-pipelines/RunEphemeralACI.template.json | envsubst > pipeline.json
        cat infra/adf-triggers/DailyTrigger.template.json | envsubst > trigger.json
        echo "Generated trigger.json:"
        cat trigger.json
    - name: Deploy pipeline to ADF
      run: |
        az datafactory pipeline create \
          --factory-name $ADF_NAME \
          --resource-group $RESOURCE_GROUP \
          --name $ADF_PIPELINE_NAME \
          --pipeline @pipeline.json

    - name: Deploy ADF trigger
      run: |
        az datafactory trigger create \
          --factory-name "$ADF_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          --name "$TRIGGER_NAME" \
          --properties @"trigger.json"
        
    - name: Start trigger
      run: |
        az datafactory trigger start \
          --factory-name "$ADF_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          --name "$TRIGGER_NAME"